import {db,auth,ref,push,set,update,remove,onValue,get,signInWithEmailAndPassword,signOut,school,classes,toast,esc,fmt,audit,add,avg,recommended} from "../shared/firebase.js";
const $=id=>document.getElementById(id); let students={},teachers={},grades={},homeworks={}; 
classes.forEach(c=>{for(const id of ["studentClass","gradeClass","reportClass"]){const e=$(id);if(e)e.innerHTML+=`<option>${c}</option>`}});
function showTab(id){document.querySelectorAll(".section").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.tab===id))}
document.querySelectorAll(".nav").forEach(x=>x.onclick=()=>showTab(x.dataset.tab));
$("loginBtn").onclick=async()=>{let email=$("email").value.trim(),pass=$("pass").value; if(email==="director"&&pass==="9985"){toast("Для первого входа создай Firebase Auth пользователя director с нужным e-mail.");$("err").style.display="block";$("err").textContent="Firebase Authentication требует e-mail. Введи e-mail директора.";return} try{await signInWithEmailAndPassword(auth,email,pass);$("login").style.display="none";$("app").style.display="block";load()}catch(e){$("err").style.display="block";$("err").textContent=e.message}};
$("logout").onclick=()=>signOut(auth);
function load(){onValue(ref(db,"students"),s=>{students=s.val()||{};renderStudents();fillAccess();metrics()});onValue(ref(db,"teachers"),s=>{teachers=s.val()||{};renderTeachers();fillAccess();metrics()});onValue(ref(db,"grades"),s=>{grades=s.val()||{};metrics();renderGradePanel()});onValue(ref(db,"homework"),s=>{homeworks=s.val()||{};renderHomework()});onValue(ref(db,"announcements"),s=>renderAnnouncements(s.val()||{}));onValue(ref(db,"events"),s=>renderEvents(s.val()||{}));onValue(ref(db,"audit"),s=>renderAudit(s.val()||{}))}
function metrics(){ $("mStudents").textContent=Object.keys(students).length;$("mTeachers").textContent=Object.keys(teachers).length;let a=[];Object.values(grades).forEach(g=>a.push(+g.grade));$("mGrades").textContent=a.length;$("mAvg").textContent=avg(a)?avg(a).toFixed(2):"—";$("alerts").innerHTML=a.filter(x=>x===2).length>5?`<b>Внимание:</b> в журнале ${a.filter(x=>x===2).length} оценок «2».`:"Критических предупреждений нет."}
function renderStudents(){let q=($("studentSearch").value||"").toLowerCase(),c=$("studentClass").value; $("studentRows").innerHTML=Object.entries(students).filter(([id,s])=>(!q||s.fullName?.toLowerCase().includes(q))&&(!c||s.class===c)).map(([id,s])=>`<tr><td>${esc(s.fullName)}</td><td>${esc(s.birthDate)}</td><td><span class=pill>${esc(s.class)}</span></td><td><button class=ghost onclick="window.deleteStudent('${id}')">Удалить</button></td></tr>`).join("")||"<tr><td colspan=4>Нет данных</td></tr>"}
window.deleteStudent=async id=>{if(confirm("Удалить ученика?")){await remove(ref(db,"students/"+id));await audit("Удаление ученика",id)}};
$("studentSearch").oninput=renderStudents;$("studentClass").onchange=renderStudents;
$("addStudent").onclick=()=>openModal(`<h2>Добавить ученика</h2><div class=formgrid><input id=fio class="input full" placeholder="ФИО"><input id=birth class=input type=date><select id=cl class=select>${classes.map(c=>`<option>${c}</option>`).join("")}</select></div><button id=saveStudent class=primary style="margin-top:14px">Добавить</button>`);
function renderTeachers(){let q=($("teacherSearch").value||"").toLowerCase();$("teacherRows").innerHTML=Object.entries(teachers).filter(([id,t])=>!q||t.fullName?.toLowerCase().includes(q)).map(([id,t])=>`<tr><td>${esc(t.fullName)}</td><td>${esc((t.subjects||[]).join(", "))}</td><td>${esc((t.classes||[]).join(", "))}</td><td><button class=danger onclick="window.deleteTeacher('${id}')">Удалить</button></td></tr>`).join("")||"<tr><td colspan=4>Нет данных</td></tr>"}
window.deleteTeacher=async id=>{if(confirm("Удалить учителя?")){await remove(ref(db,"teachers/"+id));await audit("Удаление учителя",id)}};$("teacherSearch").oninput=renderTeachers;
$("addTeacher").onclick=()=>openModal(`<h2>Добавить учителя</h2><input id=tfio class=input style="width:100%" placeholder="ФИО"><input id=tsub class=input style="width:100%;margin-top:10px" placeholder="Предметы через запятую"><select id=tcls multiple class=select style="width:100%;margin-top:10px;height:130px">${classes.map(c=>`<option>${c}</option>`).join("")}</select><button id=saveTeacher class=primary style="margin-top:14px">Добавить</button>`);
$("modal").addEventListener("click",e=>{if(e.target.id==="saveStudent"){add("students",{fullName:$("fio").value,birthDate:$("birth").value,class:$("cl").value,createdAt:Date.now()});closeModal();audit("Добавление ученика",$("fio").value)}if(e.target.id==="saveTeacher"){add("teachers",{fullName:$("tfio").value,subjects:$("tsub").value.split(",").map(x=>x.trim()).filter(Boolean),classes:[...$("tcls").selectedOptions].map(x=>x.value),createdAt:Date.now()});closeModal();audit("Добавление учителя",$("tfio").value)}});
function renderGradePanel(){let c=$("gradeClass").value;if(!c){$("gradePanel").innerHTML="<div class=card>Выберите класс.</div>";return}let arr=Object.entries(students).filter(([id,s])=>s.class===c);$("gradePanel").innerHTML=arr.map(([id,s])=>{let gs=Object.values(grades).filter(g=>g.studentId===id);let a=avg(gs.map(g=>g.grade));return `<div class=card style="margin-bottom:10px"><b>${esc(s.fullName)}</b><span class=pill style="margin-left:8px">${a?a.toFixed(2):"нет оценок"}</span><div class=muted style="margin-top:8px">${gs.map(g=>`${esc(g.subject||"—")}: ${g.grade} · ${esc(g.type||"")} · ${fmt(g.date)}`).join("<br>")||"Оценок нет"}</div></div>`}).join("")||"<div class=card>Ученики не найдены.</div>"}
$("gradeClass").onchange=renderGradePanel;
function fillAccess(){$("accessStudent").innerHTML=Object.entries(students).map(([id,s])=>`<option value="${id}">${esc(s.fullName)} — ${s.class}</option>`).join("");$("accessTeacher").innerHTML=Object.entries(teachers).map(([id,t])=>`<option value="${id}">${esc(t.fullName)}</option>`).join("")}
function gen(){return Math.random().toString(36).slice(2,8)+"-"+Math.random().toString(36).slice(2,6)}
$("genStudent").onclick=async()=>{let id=$("accessStudent").value;if(!id)return;let login="student_"+id.slice(0,6),pass=gen();await update(ref(db,"students/"+id),{login});$("studentAccessResult").innerHTML=`<div class=card style="margin-top:12px"><b>Логин:</b> ${login}<br><b>Пароль:</b> ${pass}<br><small>Для реальной авторизации создай Firebase Auth account с e-mail/логином.</small></div>`;audit("Выдан доступ ученику",id)};
$("genTeacher").onclick=async()=>{let id=$("accessTeacher").value;if(!id)return;let login="teacher_"+id.slice(0,6),pass=gen();await update(ref(db,"teachers/"+id),{login});$("teacherAccessResult").innerHTML=`<div class=card style="margin-top:12px"><b>Логин:</b> ${login}<br><b>Пароль:</b> ${pass}</div>`;audit("Выдан доступ учителю",id)};
function renderHomework(h){$("homeworkRows").innerHTML=Object.values(h).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)).map(x=>`<div class=card style="margin-bottom:10px"><b>${esc(x.subject)} · ${esc(x.class)}</b><p>${esc(x.text)}</p><span class=pill>до ${esc(x.dueDate||"—")}</span></div>`).join("")||"<div class=card>Нет Д/З.</div>"}
function renderAnnouncements(a){$("annRows").innerHTML=Object.values(a).sort((x,y)=>(y.createdAt||0)-(x.createdAt||0)).map(x=>`<div class=card style="margin-bottom:10px"><b>${x.pinned?"📌 ":""}${esc(x.title)}</b><p>${esc(x.text)}</p></div>`).join("")}
$("addAnn").onclick=async()=>{await add("announcements",{title:$("annTitle").value,text:$("annText").value,pinned:true,createdAt:Date.now()});$("annTitle").value=$("annText").value="";toast("Объявление опубликовано")};
function renderEvents(e){$("eventRows").innerHTML=Object.values(e).sort((a,b)=>a.date?.localeCompare(b.date)).map(x=>`<div class=card style="margin-bottom:8px"><b>${esc(x.date)}</b> — ${esc(x.title)}</div>`).join("")}
$("addEvent").onclick=async()=>{await add("events",{date:$("eventDate").value,title:$("eventTitle").value});$("eventTitle").value="";toast("Событие добавлено")};
function renderAudit(a){$("auditRows").innerHTML=Object.values(a).sort((x,y)=>(y.time||0)-(x.time||0)).slice(0,100).map(x=>`<div class=card style="margin-bottom:7px"><b>${esc(x.action)}</b><br>${esc(x.details)}<br><span class=muted>${fmt(x.time)}</span></div>`).join("")}
$("classReport").onclick=()=>{let c=$("reportClass").value;let arr=Object.entries(students).filter(([id,s])=>s.class===c);$("report").innerHTML=`<h3>Отчёт по классу ${c}</h3>`+arr.map(([id,s])=>{let gs=Object.values(grades).filter(g=>g.studentId===id);return `<div class=card style="margin-bottom:8px">${esc(s.fullName)} — <b>${avg(gs.map(g=>g.grade))?avg(gs.map(g=>g.grade)).toFixed(2):"—"}</b></div>`}).join("")};
$("printReport").onclick=()=>window.print();$("exportReport").onclick=()=>{let rows=[["ФИО","Класс","Средний балл"]];Object.entries(students).forEach(([id,s])=>{let gs=Object.values(grades).filter(g=>g.studentId===id);rows.push([s.fullName,s.class,avg(gs.map(g=>g.grade)).toFixed(2)])});let csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\\ufeff"+csv],{type:"text/csv"}));a.download="otchet.csv";a.click()};
function openModal(html){$("modalContent").innerHTML=html;$("modal").classList.add("open")}function closeModal(){$("modal").classList.remove("open")}$("closeModal").onclick=closeModal;
